lpongetti/flutter_map_marker_cluster

README.md
The example provided on README didn't match the one in the `/example` folder. Now it's good again!
=> Update README with new size param

lib/src/marker_cluster_layer.dart, lib/src/marker_cluster_layer_options.dart
This adds an optional onMarkerTap callback which gets triggered when
tapping a marker. My motivation is as follows:
I have an app which shows a popup when a marker is tapped. Originally I
implemented this by wrapping an Icon in a GestureBuilder in the Marker's
child Widget only to discover that only one GestureBuilder will get
triggered per gesture event (in this case tap). This meant that my
popups broke the centerMarkerOnClick functionality.
=> Add optional onTap callback for Markers

example/.flutter-plugins-dependencies, example/lib/main.dart, lib/flutter_map_marker_cluster.dart, lib/src/marker_cluster_layer.dart, lib/src/marker_cluster_layer_options.dart, lib/src/node/marker_cluster_node.dart, pubspec.yaml
Adds the ability to show a customisable popup Widget for a marker. This
is shown when tapping a marker and it can also be controlled using the
PopupController (see the example).
Popups are hidden when the popup is clustered or 'unspiderfyed'.
**Note:**
There is a commit containing spelling fixes, if you don't want to include that let me know and I'll remove it: https://github.com/lpongetti/flutter_map_marker_cluster/commit/6d3486067e27cf3feb26163a424df75be272ae8d
There is also a commit from an older PR that didn't get merged (#37) which I left in because it added some code that this popup needs. If you don't want to merge the onMarkersClustered change I can also remove that.
If you want to see an example of a more 'fancy' popup have a look at the example in: …
=> Add popups

lib/src/node/marker_node.dart
I opened a [PR](https://github.com/johnpryan/flutter_map/pull/553) on `flutter_map` repo introducing `Marker.extras` property. 
So we need this update here too as soon as the `flutter_map` package includes this update. 
For context: I needed to add extra properties to markers (so I can sum this props to show a total number on the cluster).
Please tell me if I need to change anything.
Thanks!
=> Add extras property override to markers to match flutter_map

lib/src/marker_cluster_layer.dart
When you zoom or pan the map, the order and number of markers might change from one build to the next. As a result the matching of widget tree and element tree is not optimal. When using stateful widgets as markers, the widget-state connection is updated often resulting in unnecessary builds.
Simply adding a key solves this issue.
=> add key so that states are preserved when map moves

pubspec.yaml
There is a new version `^0.11.0` which has vast improvements. My suggestion is to support up to major change if there are no contraindications I'm not aware of.
=> Add support for newest version of flutter_map dep

lib/src/marker_cluster_layer.dart
I noticed that sometimes when tapping a cluster it would not uncluster.
I wrote this fix a while ago but it felt a bit hacky so I didn't open a pull-request however I thought I should at least share it with you so that you/others are aware.
---
From memory the issue is that it's possible that the new calculated zoom level is slightly less than the cluster's zoom level so the zoom/uncluster animation would start but then it would zoom back out and the uncluster would not happen.
I have an app with ~1300 markers and I came upon this issue randomly, unfortunately I didn't capture it in a reproducible way so it's not very easy to test. However since adding this fix I haven't run in to the issue again.
Adding 0.0000001 was necessary as sometimes the new zoom would exactly equal the cluster …
=> Ensure cluster is split when tapping it

lib/flutter_map_marker_cluster.dart, lib/src/marker_cluster_layer_widget.dart
[flutter_map](https://pub.dev/packages/flutter_map) changed the way of adding layers to the map. Previously, `layers` were added via the `layer` property, now there is a `children` property. For this `children` property we need specific widgets, like the `MarkerLayerWidget` provided by the [flutter_map](https://pub.dev/packages/flutter_map). With the created `MarkerClusterLayerWidget` we can now use the new way and provide a specific widget to the `children` property.
```
########## old way:
FlutterMap(
plugins: [
MarkerClusterPlugin(),
],
layers: [
TileLayerOptions(),
MarkerClusterLayerOptions(),
],
);
########## new way:
FlutterMap(
plugins: [
MarkerClusterPlugin(),
],
children: [
TileLayerWidget(
options: TileLayerOptions(),
),
MarkerClusterLayerWidget(
options: …
```
=> MarkerClusterLayerWidget added to support the new way to create layers for the flutter map (with widgets)

CHANGELOG.md, example/lib/main.dart, lib/src/marker_cluster_layer.dart, lib/src/marker_cluster_layer_options.dart, pubspec.yaml
Support multiple visible popups at once. The default behaviour remains
single-popup but some breaking changes in PopupController were required:
- hidePopups -> hideAllPopups
- hidePopupIfShowingFor -> hidePopupsOnlyFor
- showPopup -> showPopupsOnlyFor
If you wish to show multiple popups at once you will want to change the
default MarkerTapBehavior, see the documentation in PopupMarkerLayerOptions.
@lpongetti Note I haven't changed the version number in CHANGELOG.md or pubspec,yaml as I'm not sure if you will want to bump the minor or major version number. I bumped the major version (to v2) in `flutter_map_marker_popup` since there were breaking changes involved and it was a big change conceptually to allow multiple popups to be visible however since popups is just a little part of this …
=> Upgrade to flutter_map_marker_popup v2

lib/src/marker_cluster_layer.dart
When the list of markers changes, i.e. the order of elements changes or some elements are added/removed, the state of one marker widget might get matched to another marker, resulting in a loss of state for that widget. When working with FutureBuilder or StreamBuilder's for example this might result in flickering. 
This merge request solves this by setting a key to the MapWidget's.
=> prevent flickering when marker list changes

lib/src/marker_cluster_layer.dart, pubspec.yaml
Fixes: https://github.com/lpongetti/flutter_map_marker_cluster/issues/124
Also applied the same Marker disappearing fix I previously merged in to flutter_map: https://github.com/fleaflet/flutter_map/pull/1291
@lpongetti can you please merge this too while you are at it? It causes red screen as you can see from the related issue 124
I have been using this fix for the past month in a production app and no null exceptions aroused to crashlytics
=> Null check bug fix

lib/src/marker_widget.dart
The current behavior is that, when the marker list changes, all marker widgets are rebuilt without any state sharing. This is because the `MarkerWidget` uses an `ObjectKey` on the `MarkerNode`, which is always created anew.
The `MapWidget` is currently constructed with this a key as proposed in this change. I can't think of a reason why `MarkerWidget` should be different.
=> Use the marker's key to avoid rebuilding

lib/src/cluster_manager.dart, lib/src/map_calculator.dart, lib/src/marker_cluster_layer.dart, lib/src/marker_widget.dart, lib/src/node/marker_cluster_node.dart, lib/src/node/marker_node.dart, lib/src/node/marker_or_cluster_node.dart, lib/src/translate.dart
I noticed that for my use-cases I was bottle-necked by UI-thread utilization, frequently missing the 60FPS mark and starving the rasterization pipeline.
At first I took a stab with the profiler and did some micro-optimizations with some small success (though hope the code got a bit simpler too). Afterwards, I realized that the node-trees geographical partitioning is greatly suited to reduce the amount of work that needs to be done. Today, we're going though all markers to then cull them if they're not on screen. However we can dismiss entire clusters early.
Measured widget build times:
* Before: 1446.1636363636364 +/- 480.1128944372966
* After:  1453.418181818182 +/- 336.8953811663788
i.e. a 87% reduction. However, looking at the performance overlay implies the impact is even larger …
=> Performance: almost 90% reduction in Widget build times

lib/src/cluster_manager.dart, lib/src/marker_cluster_layer.dart, lib/src/node/marker_cluster_node.dart
Hey, thanks for merging my previous change. This is another improvement I had lined up. While the other change did improve the frame-to-frame rebuilds by reducing the latitude of the tree traversal, this change is geared towards improving the initial build time. This is useful whenever you change the set of markers, e.g. loading new markers when panning around.
Thanks!
=> Avoid some duplicate/throw-away work during initial cluster tree construction.

lib/src/cluster_manager.dart, lib/src/marker_cluster_layer.dart, lib/src/node/marker_cluster_node.dart
FlutterMap 3.2 makes LatLngBounds non-nullable, which means we'll have to change how we initialize bounds across the marker/cluster hierarchy.
Let me know if you'd like me to split this out from the other changes.
=> Null safe latlngbounds

lib/src/marker_cluster_layer.dart, lib/src/marker_widget.dart
As mentioned in https://github.com/lpongetti/flutter_map_marker_cluster/issues/153 the popup-feature is broken after 1.0.1.
This change fixes so that the popup-feature works again, however, it should be reviewed by someone with more insight on what could potentially break (possibly related to desktop usage)
=> Solves inability to open popup

CHANGELOG.md, example/lib/clustering_many_markers_page.dart, example/lib/clustering_page.dart, example/pubspec.yaml, lib/src/cluster_manager.dart, lib/src/core/util.dart, lib/src/map_calculator.dart, lib/src/marker_cluster_layer.dart, lib/src/marker_cluster_layer_options.dart, lib/src/marker_cluster_layer_widget.dart, lib/src/marker_widget.dart, lib/src/node/marker_cluster_node.dart, lib/src/node/marker_node.dart, lib/src/node/marker_or_cluster_node.dart, lib/src/translate.dart, pubspec.yaml, test/distance_grid_test.dart
Hey folks! I tried switching to flutter_map v6.0.0, but flutter_map_popup for this version isn't out yet. Can someone take a look and help improve this PR?
There are also some deprecated classes that we still use like FitBoundsOptions or mapController.centerZoomFitBounds.
Thanks a bunch!
=> flutter map version 6, waiting flutter_map_popup

lib/src/marker_cluster_layer.dart
When navigating on the map (without zoom), all marker are rebuild all the time (cf Flutter performance tab)
Add an ObjectValue as key to let framework recover the Widget and avoid to rebuild it
=> Avoid all cluster marker to be rebuild when navigating on map

lib/src/marker_cluster_layer.dart
Currently if you tap on a cluster and your map bounds are already 'fit' then you will wait the full length of the animation duration before the spiderfy begins. This PR makes it such that if the bounds are already fit, (aka there won't be any map movement on tap), then skip the animation and immediately spiderfy, making the spiderfy feel a lot snappier.
=> Don't fitBounds before spiderfy if bounds are already fit

lib/src/marker_cluster_layer.dart
Previously if you clicked on a cluster and they were spiderfied, they could be built underneath nearby markers / clusters. This PR ensures they are built above them.
=> Build spiderfy layers on top of other markers and clusters

lib/src/marker_cluster_layer.dart
The marker popups didn't rotate correctly as the `PopupLayer` was wrapped into a `MobileLayerTransformer` while it has its own internally.
Moved the `PopupLayer` outside the `MobileLayerTransformer`: https://github.com/tratteo/flutter_map_marker_cluster/blob/d0a996c0d48ff5eeac54273667ac2023a2fc4a2a/lib/src/marker_cluster_layer.dart#L153
=> PopupLayer rotation fix

README.md
Subdomains usage is deprecated: https://github.com/openstreetmap/operations/issues/737
=> Remove subdomains from OSM urlTemplate

lib/src/marker_cluster_layer.dart, lib/src/marker_cluster_layer_options.dart, lib/src/marker_widget.dart
Added simple way to opt out using GestureDetector for MarkerWidget  as it is interfering with gesture detector behavior provided by MarkerChild. 
This functionality  was needed as Marker I made have a custom GestureDtetector that reacts on events only within marker shape.
=> Add markerChildBehavior option to MarkerWidget

lib/src/marker_cluster_layer.dart, lib/src/marker_cluster_layer_options.dart, lib/src/marker_widget.dart
I'd like to introduce a zoom to marker feature when a marker is double tapped. Without adding a gesture detector over the top of the marker there isn't a way to do this.
This PR exposes the double tap method of the marker's GestureDetector for use.
=> Add marker double tap

lib/src/map_calculator.dart
Hi there!
I would like to use the newest prerelease of flutter_map and came across an issue with the Point class of dart:math because the subtract method is not supported anymore.
Looking forward for a new release 😊
=> Support for flutter_map prerelease version 7.0.0-dev.1

lib/src/marker_cluster_layer.dart, lib/src/marker_cluster_layer_options.dart, pubspec.yaml
**This merge is blocked by the release of [this](https://github.com/rorystephenson/flutter_map_marker_popup/pull/78) flutter_map_marker_popup pr** 
- migrated PolygonOptions isDotted to pattern as the flutter_map Polygon now uses pattern instead of a bool flag for line styling
=> Migration to flutter map v7

lib/src/marker_cluster_layer.dart, lib/src/marker_widget.dart
An onDoubleTap feature was recently added to the marker widget. This causes a delay in the onTap action because the GestureDetector waits to see if the user will double tap. To fix this, set the default value of onDoubleTap to null and make it optional. This way, the onTap action will not be delayed if onDoubleTap is null.
=> fix: Fix onTap marker delay issue
